name: deploy

on:
  push:
    branches:
      - master

jobs:
  run:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: callmehan/money-saver:${{ github.sha }}
      - name: Update Container
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: deployment/
          playbook: main.yml
          requirements: requirements.yml
          key: ${{secrets.REMOTE_SERVER_PRIVATE_KEY}}
          options: |
            --inventory hosts
            --extra-vars IMAGE_TAG=${{ github.sha }}
            --extra-vars REMOTE_SERVER_IP=${{ secrets.REMOTE_SERVER_IP }}
            --extra-vars WECHAT_OA_TOKEN=${{ secrets.WECHAT_OA_TOKEN }}
            --extra-vars WECHAT_OA_APP_ID=${{ secrets.WECHAT_OA_APP_ID }}
            --extra-vars WECHAT_OA_AES=${{ secrets.WECHAT_OA_AES }}
            --extra-vars TBK_APPKEY=${{ secrets.TBK_APPKEY }}
            --extra-vars TBK_APP_SECRET=${{ secrets.TBK_APP_SECRET }}
            --extra-vars TBK_ADZONE_ID=${{ secrets.TBK_ADZONE_ID }}
            --verbose
